## üêõ Bug Report

**Description**
A clear and concise description of what the bug is.

**Environment**
- Python version: [e.g. 3.11.0]
- Instagram Analyzer version: [e.g. 0.2.1]
- Operating system: [e.g. Ubuntu 22.04, Windows 11, macOS 13]
- Installation method: [Poetry, pip, etc.]

**To Reproduce**
Steps to reproduce the behavior:
1. Load Instagram export data from '...'
2. Run command '...'
3. See error

**Expected Behavior**
A clear and concise description of what you expected to happen.

**Actual Behavior**
A clear and concise description of what actually happened.

**Error Messages**
If applicable, paste the full error message and traceback:

```
Paste error message here
```

**Sample Data (if relevant)**
If relevant to the issue, provide:
- Size of your Instagram export
- Types of data included (posts, stories, etc.)
- Approximate date range of the data
- **Note**: Do not include actual personal data

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional Context**
Add any other context about the problem here.

**Checklist**
- [ ] I have searched for existing issues that might be related
- [ ] I have tried with the latest version
- [ ] I have included all relevant information above
- [ ] I have not included any personal or sensitive data
